/* 常用符号表 —— 用于输入框自动联想（纯本地匹配，无网络依赖）。
 * 每条格式：[TradingView代码, 显示名, 类别]  类别: us / cn / crypto / gold
 * 可自行增删。 */
window.SYMBOL_DB = [
  // ===== 虚拟币（BINANCE 计价币为 USDT）=====
  ["BINANCE:BTCUSDT", "比特币 BTC", "crypto"],
  ["BINANCE:ETHUSDT", "以太坊 ETH", "crypto"],
  ["BINANCE:BNBUSDT", "币安币 BNB", "crypto"],
  ["BINANCE:SOLUSDT", "Solana SOL", "crypto"],
  ["BINANCE:XRPUSDT", "瑞波 XRP", "crypto"],
  ["BINANCE:ADAUSDT", "艾达币 ADA", "crypto"],
  ["BINANCE:DOGEUSDT", "狗狗币 DOGE", "crypto"],
  ["BINANCE:TRXUSDT", "波场 TRX", "crypto"],
  ["BINANCE:TONUSDT", "Toncoin TON", "crypto"],
  ["BINANCE:AVAXUSDT", "雪崩 AVAX", "crypto"],
  ["BINANCE:DOTUSDT", "波卡 DOT", "crypto"],
  ["BINANCE:LINKUSDT", "Chainlink LINK", "crypto"],
  ["BINANCE:SHIBUSDT", "柴犬币 SHIB", "crypto"],
  ["BINANCE:LTCUSDT", "莱特币 LTC", "crypto"],
  ["BINANCE:BCHUSDT", "比特币现金 BCH", "crypto"],
  ["BINANCE:UNIUSDT", "Uniswap UNI", "crypto"],
  ["BINANCE:NEARUSDT", "NEAR", "crypto"],
  ["BINANCE:APTUSDT", "Aptos APT", "crypto"],
  ["BINANCE:ICPUSDT", "ICP", "crypto"],
  ["BINANCE:XLMUSDT", "恒星币 XLM", "crypto"],
  ["BINANCE:FILUSDT", "Filecoin FIL", "crypto"],
  ["BINANCE:ETCUSDT", "以太经典 ETC", "crypto"],
  ["BINANCE:ATOMUSDT", "Cosmos ATOM", "crypto"],
  ["BINANCE:INJUSDT", "Injective INJ", "crypto"],
  ["BINANCE:OPUSDT", "Optimism OP", "crypto"],
  ["BINANCE:ARBUSDT", "Arbitrum ARB", "crypto"],
  ["BINANCE:SUIUSDT", "Sui SUI", "crypto"],
  ["BINANCE:SEIUSDT", "Sei SEI", "crypto"],
  ["BINANCE:TIAUSDT", "Celestia TIA", "crypto"],
  ["BINANCE:RUNEUSDT", "THORChain RUNE", "crypto"],
  ["BINANCE:PEPEUSDT", "Pepe PEPE", "crypto"],
  ["BINANCE:WIFUSDT", "dogwifhat WIF", "crypto"],
  ["BINANCE:FTMUSDT", "Fantom FTM", "crypto"],
  ["BINANCE:AAVEUSDT", "Aave AAVE", "crypto"],
  ["BINANCE:MKRUSDT", "Maker MKR", "crypto"],
  ["BINANCE:CRVUSDT", "Curve CRV", "crypto"],
  ["BINANCE:GRTUSDT", "The Graph GRT", "crypto"],
  ["BINANCE:SANDUSDT", "The Sandbox SAND", "crypto"],
  ["BINANCE:MANAUSDT", "Decentraland MANA", "crypto"],
  ["BINANCE:AXSUSDT", "Axie AXS", "crypto"],
  ["BINANCE:EOSUSDT", "EOS", "crypto"],
  ["BINANCE:THETAUSDT", "Theta THETA", "crypto"],
  ["BINANCE:HBARUSDT", "Hedera HBAR", "crypto"],
  ["BINANCE:XTZUSDT", "Tezos XTZ", "crypto"],
  ["BINANCE:EGLDUSDT", "MultiversX EGLD", "crypto"],
  ["BINANCE:FLOWUSDT", "Flow FLOW", "crypto"],
  ["BINANCE:CROUSDT", "Cronos CRO", "crypto"],
  ["BINANCE:LDOUSDT", "Lido LDO", "crypto"],
  ["BINANCE:ARUSDT", "Arweave AR", "crypto"],
  ["BINANCE:RNDRUSDT", "Render RNDR", "crypto"],
  ["BINANCE:STXUSDT", "Stacks STX", "crypto"],
  ["COINBASE:USDTUSD", "泰达币 USDT", "crypto"],
  ["COINBASE:USDTUSDC", "USDT/USDC", "crypto"],
  ["BINANCE:USDCUSDT", "USD Coin USDC", "crypto"],

  // ===== 美股 =====
  ["NASDAQ:AAPL", "苹果 Apple", "us"],
  ["NASDAQ:MSFT", "微软 Microsoft", "us"],
  ["NASDAQ:GOOGL", "谷歌 Google", "us"],
  ["NASDAQ:AMZN", "亚马逊 Amazon", "us"],
  ["NASDAQ:NVDA", "英伟达 NVIDIA", "us"],
  ["NASDAQ:META", "Meta", "us"],
  ["NASDAQ:TSLA", "特斯拉 Tesla", "us"],
  ["NASDAQ:AVGO", "博通 Broadcom", "us"],
  ["NYSE:BRK.B", "伯克希尔 Berkshire", "us"],
  ["NYSE:JPM", "摩根大通 JPMorgan", "us"],
  ["NYSE:V", "Visa", "us"],
  ["NYSE:UNH", "联合健康 UnitedHealth", "us"],
  ["NYSE:XOM", "埃克森美孚 Exxon", "us"],
  ["NYSE:JNJ", "强生 Johnson&Johnson", "us"],
  ["NYSE:PG", "宝洁 P&G", "us"],
  ["NYSE:MA", "万事达 Mastercard", "us"],
  ["NYSE:HD", "家得宝 Home Depot", "us"],
  ["NASDAQ:COST", "好市多 Costco", "us"],
  ["NYSE:ABBV", "艾伯维 AbbVie", "us"],
  ["NYSE:MRK", "默沙东 Merck", "us"],
  ["NYSE:KO", "可口可乐 Coca-Cola", "us"],
  ["NASDAQ:PEP", "百事 Pepsi", "us"],
  ["NYSE:BAC", "美国银行 Bank of America", "us"],
  ["NYSE:WMT", "沃尔玛 Walmart", "us"],
  ["NASDAQ:NFLX", "奈飞 Netflix", "us"],
  ["NYSE:DIS", "迪士尼 Disney", "us"],
  ["NASDAQ:ADBE", "Adobe", "us"],
  ["NYSE:CRM", "赛富时 Salesforce", "us"],
  ["NASDAQ:CSCO", "思科 Cisco", "us"],
  ["NASDAQ:INTC", "英特尔 Intel", "us"],
  ["NASDAQ:AMD", "AMD", "us"],
  ["NASDAQ:QCOM", "高通 Qualcomm", "us"],
  ["NASDAQ:TXN", "德州仪器 TI", "us"],
  ["NYSE:ORCL", "甲骨文 Oracle", "us"],
  ["NYSE:IBM", "IBM", "us"],
  ["NYSE:ACN", "埃森哲 Accenture", "us"],
  ["NYSE:GE", "通用电气 GE", "us"],
  ["NYSE:CAT", "卡特彼勒 Caterpillar", "us"],
  ["NYSE:BA", "波音 Boeing", "us"],
  ["NYSE:MCD", "麦当劳 McDonald's", "us"],
  ["NYSE:NKE", "耐克 Nike", "us"],
  ["NASDAQ:SBUX", "星巴克 Starbucks", "us"],
  ["NYSE:T", "AT&T", "us"],
  ["NYSE:VZ", "威瑞森 Verizon", "us"],
  ["NYSE:PFE", "辉瑞 Pfizer", "us"],
  ["NYSE:LLY", "礼来 Eli Lilly", "us"],
  ["NYSE:NVO", "诺和诺德 Novo Nordisk", "us"],
  ["NASDAQ:BABA", "阿里巴巴 Alibaba", "us"],
  ["NASDAQ:PDD", "拼多多 PDD", "us"],
  ["NASDAQ:JD", "京东 JD.com", "us"],
  ["NASDAQ:BILI", "哔哩哔哩 Bilibili", "us"],
  ["NASDAQ:NIO", "蔚来 NIO", "us"],
  ["NASDAQ:XPEV", "小鹏 Xpeng", "us"],
  ["NASDAQ:LI", "理想汽车 Li Auto", "us"],
  ["NASDAQ:SPY", "标普500 ETF SPY", "us"],
  ["NASDAQ:QQQ", "纳斯达克100 ETF QQQ", "us"],
  ["NYSE:VOO", "标普500 ETF VOO", "us"],
  ["NYSE:DIA", "道指 ETF DIA", "us"],

  // ===== A股 =====
  ["SSE:600519", "贵州茅台", "cn"],
  ["SZSE:000858", "五粮液", "cn"],
  ["SSE:601318", "中国平安", "cn"],
  ["SSE:600036", "招商银行", "cn"],
  ["SSE:601398", "工商银行", "cn"],
  ["SSE:601288", "农业银行", "cn"],
  ["SSE:601988", "中国银行", "cn"],
  ["SSE:601166", "兴业银行", "cn"],
  ["SZSE:000001", "平安银行", "cn"],
  ["SSE:600900", "长江电力", "cn"],
  ["SSE:601899", "紫金矿业", "cn"],
  ["SSE:600028", "中国石化", "cn"],
  ["SSE:601857", "中国石油", "cn"],
  ["SSE:600030", "中信证券", "cn"],
  ["SSE:601688", "华泰证券", "cn"],
  ["SSE:601012", "隆基绿能", "cn"],
  ["SZSE:300750", "宁德时代", "cn"],
  ["SZSE:002594", "比亚迪", "cn"],
  ["SSE:600276", "恒瑞医药", "cn"],
  ["SZSE:300059", "东方财富", "cn"],
  ["SZSE:000333", "美的集团", "cn"],
  ["SZSE:000651", "格力电器", "cn"],
  ["SSE:600887", "伊利股份", "cn"],
  ["SSE:601888", "中国中免", "cn"],
  ["SSE:603288", "海天味业", "cn"],
  ["SSE:601628", "中国人寿", "cn"],
  ["SSE:601601", "中国太保", "cn"],
  ["SSE:600031", "三一重工", "cn"],
  ["SSE:601390", "中国中铁", "cn"],
  ["SSE:601668", "中国建筑", "cn"],
  ["SSE:600585", "海螺水泥", "cn"],
  ["SSE:601919", "中远海控", "cn"],
  ["SSE:600104", "上汽集团", "cn"],
  ["SSE:601633", "长城汽车", "cn"],
  ["SZSE:002415", "海康威视", "cn"],
  ["SZSE:002475", "立讯精密", "cn"],
  ["SZSE:300124", "汇川技术", "cn"],
  ["SSE:688981", "中芯国际", "cn"],
  ["SSE:603501", "韦尔股份", "cn"],
  ["SSE:600309", "万华化学", "cn"],
  ["SSE:601138", "工业富联", "cn"],
  ["SSE:601088", "中国神华", "cn"],
  ["SSE:600690", "海尔智家", "cn"],

  // ===== 黄金 / 贵金属 =====
  ["TVC:GOLD", "现货黄金", "gold"],
  ["COMEX:GC1!", "COMEX 黄金期货", "gold"],
  ["OANDA:XAUUSD", "黄金/美元 XAUUSD", "gold"],
  ["TVC:SILVER", "现货白银", "gold"],
  ["COMEX:SI1!", "COMEX 白银期货", "gold"],
  ["OANDA:XAGUSD", "白银/美元 XAGUSD", "gold"],
  ["TVC:PLATINUM", "铂金", "gold"],
  ["TVC:PALLADIUM", "钯金", "gold"],
];
